'use client';

import { Shield, Infinity, Clock, Car, LucideIcon } from 'lucide-react';

interface FlipCardProps {
  icon: LucideIcon;
  title: string;
  description: string;
}

const FlipCard = ({ icon: Icon, title, description }: FlipCardProps) => {
  return (
    <div className="h-64 w-full [perspective:1000px]">
      <div className="relative h-full w-full transition-transform duration-700 [transform-style:preserve-3d] hover:[transform:rotateY(180deg)]">
        {/* Front Side - White */}
        <div className="absolute inset-0 w-full h-full [backface-visibility:hidden]">
          <div className="flex flex-col items-center justify-center h-full bg-white rounded-lg shadow-lg p-6 text-center border border-gray-200">
            <div className="mb-4 text-gray-700">
              <Icon size={48} strokeWidth={1.5} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-3">{title}</h3>
            <p className="text-gray-600 text-sm leading-relaxed">{description}</p>
          </div>
        </div>

        {/* Back Side - Red */}
        <div className="absolute inset-0 w-full h-full [backface-visibility:hidden] [transform:rotateY(180deg)]">
          <div className="flex flex-col items-center justify-center h-full bg-red-600 rounded-lg shadow-lg p-6 text-center">
            <h3 className="text-xl font-bold text-white mb-3">{title}</h3>
            <p className="text-white text-sm leading-relaxed">{description}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

const TyresSection = () => {
  const features = [
    {
      icon: Shield,
      title: "Enhanced Safety",
      description: "Quality tyres improve grip and traction, reducing braking distances and improving control, especially in challenging weather."
    },
    {
      icon: Infinity,
      title: "Long-Lasting Durability",
      description: "Premium materials and manufacture have ensured to provide a much longer duration of usage even in high mileage scenarios."
    },
    {
      icon: Clock,
      title: "Fuel Efficiency",
      description: "High-performance tyres reduce rolling resistance, leading to better fuel economy and savings over time."
    },
    {
      icon: Car,
      title: "Comfortable Ride",
      description: "Well-crafted tyres absorb shock generated by the road and thus, provide a smoother ride and even a comfortable overall driving experience."
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50 py-16 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="text-center mb-16">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            <span className="text-red-600">High-Quality Tyres </span>
            <span className="text-gray-900">for Performance, Safety, and Comfort</span>
          </h1>
          <p className="text-gray-600 max-w-4xl mx-auto leading-relaxed">
            Tyres are among the most important safety, performance, and fuel efficiency components in vehicles. Best Auto Parts provides you with a whole range of quality selection tyres differentiated by various requirements: sometimes in order to meet the call for your vehicle, sometimes to match specific driving requirements, and at other times, suited to conditions on the road. Whether you are looking for all-season tyres, performance tyres, or off-road options, our range is designed to keep you secure on every journey. With a focus on durability and performance, every one of our tires is designed to put up with the hard stuff and make for safe and enjoyable driving experience.
          </p>
        </div>

        {/* Flip Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {features.map((feature, index) => (
            <FlipCard
              key={index}
              icon={feature.icon}
              title={feature.title}
              description={feature.description}
            />
          ))}
        </div>

        {/* Why Choose Section */}
        <div className="bg-white rounded-lg shadow-lg p-8 md:p-12 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
            Why Choose Our Quality Tyres
          </h2>
          <p className="text-gray-600 max-w-3xl mx-auto leading-relaxed mb-8">
            Premium quality tyres are essential to safe vehicle use and ideal driving performance. Better handling and stability, plus greater efficiency and comfort, make it a fundamental part of using an automobile. Best Auto Parts sources the best-quality tyres from the most prestigious brands, focused on giving the best quality and durability: you get the best value and the best performance in every set.
          </p>
          <button className="bg-red-600 hover:bg-red-700 text-white font-semibold px-8 py-3 rounded transition-colors duration-300">
            Contact Us
          </button>
        </div>
      </div>

    </div>
  );
};

export default TyresSection;